#! /usr/bin/bash

mkdir includes
mkdir srcs

echo "
#ifndef CLA_HPP
# define CLA_HPP

class Cla
{
Cla( void );
Cla( const Cla& o );
~Cla( void );
Cla& operator=( const Cla& o );
};

#endif" > includes/Cla.hpp

echo "
Cla::Cla( void ) {}
Cla::Cla( const Cla& o )
{
}
Cla::~Cla( void ) {}
Cla& operator=( const Cla& o ){}
" > srcs/Cla.cpp

